spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/mydb'
    username: root
    password: ali23
  messages:
    basename: messages
    encoding: UTF-8
  banner:
    location: banner.txt
userapi:
  services:
    url: 'http://localhost:8080/user'
